### PR TITLE
fixes #9904 - updated repomd.xml timestamps with every yum_clone publish

### PR DESCRIPTION
**Pull request by jlsherrill**

### CODE REVIEW

**Comment by jlsherrill** [comment]
still needs testing

**Comment by jlsherrill** [comment]
Tested and ready for review!

**Comment by jlsherrill** [comment]
scratch builds:
http://koji.katello.org/koji/taskinfo?taskID=245415
http://koji.katello.org/koji/taskinfo?taskID=245413

To test:

1.  Install scratch build for you os
2.  Restart all pulp services
3.  Publish content view version 1 including a rhel repo with an include filter excluding all packages named 'screen'
4.  connect a client to it and attempt to install screen (nothing should get installed)
5.  Remove the filter and republish the content view
6.  Without running yum clean all, attempt to install screen

it should be able to be installed.

**Comment by stbenjam** [comment]
ACK

**Pull request merged**
